language: minimal

sudo: false

addons:
    apt_packages:
      - lib32stdc++6

env:
  - SMVERSION=1.10

install:
  - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
  - tar -xzf $(cat sourcemod-latest-linux)

before_script:
  - cp -R configs/ scripting/ addons/sourcemod/
  - cd addons/sourcemod/scripting

  - wget "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc" -O include/tf2items.inc
  - wget "https://raw.githubusercontent.com/asherkin/SteamTools/master/plugin/steamtools.inc" -O include/steamtools.inc
  
  - sed -i -e "s/funcenum/typeset/g" include/steamtools.inc
  - sed -i -e "s/public(HTTPRequestHandle:HTTPRequest, bool:requestSuccessful, HTTPStatusCode:statusCode),/function void (HTTPRequestHandle HTTPRequest, bool requestSuccessful, HTTPStatusCode statusCode);/g" include/steamtools.inc
  - sed -i -e "s/public(HTTPRequestHandle:HTTPRequest, bool:requestSuccessful, HTTPStatusCode:statusCode, any:contextData),/function void (HTTPRequestHandle HTTPRequest, bool requestSuccessful, HTTPStatusCode statusCode, any contextData);/g" include/steamtools.inc
  
  - chmod +x ./spcomp
 
jobs:
    include:
      - stage: compile
        script:
          - ./spcomp instagib.sp
      - stage: test
        script:
          - ./spcomp instagib.sp
          - mv instagib.smx ../plugins
          - cd ~
          - wget "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
          - mkdir steamcmd
          - tar -xzf steamcmd_linux.tar.gz -C steamcmd
          - cd steamcmd
          - mkdir tf2
          - printf "login anonymous\nforce_install_dir ./tf2\napp_update 232250\nquit" > update.txt
          - ./steamcmd.sh +runscript update.txt
          - cp -R ../addons/ tf2/tf/
          - cd tf2/tf2
          - wget --input-file=https://mms.alliedmods.net/mmsdrop/1.11/mmsource-latest-linux
          - tar -xzf $(cat mmsource-latest-linux)
          - ../srcds_run +map koth_nucleus 