language: minimal

sudo: false

addons:
    apt_packages:
      - lib32stdc++6
      - libc6
      - libncurses5:i386
      - libtinfo5:i386
      - libcurl3-gnutls:i386

env:
  - SMVERSION=1.10 MMVERSION=1.11

install:
  - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
  - tar -xzf $(cat sourcemod-latest-linux)

before_script:
  - cp -R configs/ scripting/ addons/sourcemod/
  - cd addons/sourcemod/scripting

  - wget "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc" -O include/tf2items.inc
  - wget "https://raw.githubusercontent.com/asherkin/SteamTools/master/plugin/steamtools.inc" -O include/steamtools.inc
  
  - sed -i -e "s/funcenum/typeset/g" include/steamtools.inc
  - sed -i -e "s/public(HTTPRequestHandle:HTTPRequest, bool:requestSuccessful, HTTPStatusCode:statusCode),/function void (HTTPRequestHandle HTTPRequest, bool requestSuccessful, HTTPStatusCode statusCode);/g" include/steamtools.inc
  - sed -i -e "s/public(HTTPRequestHandle:HTTPRequest, bool:requestSuccessful, HTTPStatusCode:statusCode, any:contextData),/function void (HTTPRequestHandle HTTPRequest, bool requestSuccessful, HTTPStatusCode statusCode, any contextData);/g" include/steamtools.inc
  
  - chmod +x ./spcomp
 
jobs:
    include:
      - stage: compile
        script:
          - ./spcomp instagib.sp
          - wget https://builds.limetech.io/files/tf2items-1.6.4-hg279-linux.zip
          - unzip tf2items-1.6.4-hg279-linux.zip
      - stage: test
        script:
          - ./spcomp instagib.sp
          - mv instagib.smx ../plugins
          - cd ../../..
          
          - wget "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
          - mkdir steamcmd
          - tar -xzf steamcmd_linux.tar.gz -C steamcmd
          
          - cd steamcmd
          - mkdir tf2
          - ./steamcmd.sh +login anonymous +force_install_dir ./tf2 +app_update 232250 +quit
          
          - cd ..
          - cp -R addons/ steamcmd/tf2/tf/
          - cd steamcmd/tf2/tf
          
          - wget --input-file=https://mms.alliedmods.net/mmsdrop/$MMVERSION/mmsource-latest-linux
          - tar -xzf $(cat mmsource-latest-linux)
          
          - wget https://builds.limetech.io/files/tf2items-1.6.4-hg279-linux.zip
          - unzip tf2items-1.6.4-hg279-linux.zip
          
          - wget https://builds.limetech.io/files/steamtools-0.10.0-git179-54fdc51-linux.zip
          - unzip tf2items-1.6.4-hg279-linux.zip
          
          - chmod -R +w ../
          
          - ../srcds_run +map koth_nucleus 